// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Payment_Teste_Api.Context;

#nullable disable

namespace Payment_Teste_Api.Migrations
{
    [DbContext(typeof(VendaContext))]
    [Migration("20221031201256_TabelaVendaBanco")]
    partial class TabelaVendaBanco
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Payment_Teste_Api.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VendaId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("Payment_Teste_Api.Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2");

                    b.Property<int>("StatusVenda")
                        .HasColumnType("int");

                    b.Property<int?>("vendedorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("vendedorId");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("Payment_Teste_Api.Models.Vendedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendedor");
                });

            modelBuilder.Entity("Payment_Teste_Api.Models.Item", b =>
                {
                    b.HasOne("Payment_Teste_Api.Models.Venda", null)
                        .WithMany("ListaItens")
                        .HasForeignKey("VendaId");
                });

            modelBuilder.Entity("Payment_Teste_Api.Models.Venda", b =>
                {
                    b.HasOne("Payment_Teste_Api.Models.Vendedor", "vendedor")
                        .WithMany()
                        .HasForeignKey("vendedorId");

                    b.Navigation("vendedor");
                });

            modelBuilder.Entity("Payment_Teste_Api.Models.Venda", b =>
                {
                    b.Navigation("ListaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
